/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * Takes project details and returns a full 4-week X social strategy
 * @summary Generate a hackathon social playbook
 */
export const GenerateHackathonPlaybookBody = zod.object({
  projectName: zod.string(),
  description: zod.string(),
  targetAudience: zod.string(),
  techStack: zod.string(),
  teamBackground: zod.string().nullish(),
});

export const GenerateHackathonPlaybookResponse = zod.object({
  id: zod.number(),
  skillType: zod.string(),
  content: zod.string(),
  createdAt: zod.coerce.date(),
});

/**
 * Takes founder details and returns a full personal brand strategy for X
 * @summary Generate a founder personal brand playbook
 */
export const GenerateFounderBrandBody = zod.object({
  founderName: zod.string(),
  whatBuilding: zod.string(),
  background: zod.string(),
  focusArea: zod.string(),
  communicationStyle: zod.string(),
});

export const GenerateFounderBrandResponse = zod.object({
  id: zod.number(),
  skillType: zod.string(),
  content: zod.string(),
  createdAt: zod.coerce.date(),
});

/**
 * @summary List recent skill generations
 */
export const ListGenerationsResponseItem = zod.object({
  id: zod.number(),
  skillType: zod.string(),
  inputSummary: zod.string(),
  createdAt: zod.coerce.date(),
});
export const ListGenerationsResponse = zod.array(ListGenerationsResponseItem);

/**
 * Receives updates from Telegram and processes skill commands
 * @summary Telegram bot webhook receiver
 */
export const TelegramWebhookBody = zod.object({
  update_id: zod.number(),
  message: zod
    .object({
      message_id: zod.number(),
      text: zod.string().nullish(),
      chat: zod.object({
        id: zod.number(),
      }),
    })
    .optional(),
});

export const TelegramWebhookResponse = zod.object({
  ok: zod.boolean(),
});

